echo "-----------------------------------------------"

echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
sleep 3
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
echo "Follow request"
